services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: unless-stopped
    ports:
      - "5137:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}

  backend:
    image: ghcr.io/the-asind/renpy-ve-backend:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - db-data:/data
    environment:
      - DATABASE_PATH=/app/database/renpy_editor.db
      - LOG_LEVEL=info

volumes:
  db-data:
