version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - ENVIRONMENT=dev
