version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://backend:9000/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend/database:/app/database
      - db-data:/data
    environment:
      - DATABASE_PATH=/app/database/renpy_editor.db
      - LOG_LEVEL=info

volumes:
  db-data:
  node_modules:
