services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://backend:8000/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/database:/app/database
      - db-data:/data
    environment:
      - DATABASE_PATH=/app/database/renpy_editor.db
      - LOG_LEVEL=info

volumes:
  db-data:
