services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
      target: build 
    command: npm run dev -- --host 0.0.0.0 
    ports:
      - "3001:3000" 
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:9000/api
      - VITE_WS_URL=ws://localhost:9000

  backend:
    
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 9000 
    volumes:
      - ./backend:/app 
    ports: 
      - "9000:9000" 
    environment:
      - ENVIRONMENT=dev 
      
      - CORS_ORIGINS=http://localhost:3001
