global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: renpy-visual-editor-backend
    scheme: https
    metrics_path: /internal/metrics
    static_configs:
      - targets:
          - renpy.online:443
  - job_name: renpy-msk-host
    scheme: https
    metrics_path: /internal/host-metrics
    static_configs:
      - targets:
          - renpy.online:443
  - job_name: renpy-fin-backup
    metrics_path: /health.prom
    static_configs:
      - targets:
          - 127.0.0.1:19092
